-- Copyright © 2017 ns@slak.ws; see LICENSE file.
{-|
Module      : Paths_judge
Description : This file is a placeholder --- it will be automatically
              generated by Cabal during building.
License     : GPL-3
Stability   : experimental
-}

{-# LANGUAGE PackageImports #-}
module Paths_judge where

import "directory" System.Directory (makeAbsolute)

getDataDir :: IO String
getDataDir = makeAbsolute "logic"
