-- Copyright © 2017 ns@slak.ws; see LICENSE file.
{-|
Module      : Paths_judge
Description : This file is a placeholder --- it will be automatically
              generated by Cabal during building.
License     : GPL-3
Stability   : experimental
-}

{-# LANGUAGE PackageImports #-}
module Paths_judge where

import "directory" System.Directory (makeAbsolute)

getDataDir :: IO String
getDataDir = makeAbsolute "logic"

-- Normally, this file is generated by stack or cabal and the path is hardcoded 
-- into the binary, based on where the `data-files` in the .cabal package were 
-- installed. When creating a .deb or other kind of binary package, this 
-- should probably be more portable and point to /usr/share/judge or similar
